# Site settings
title: 2491 No Mythic
description: > # this means to ignore newlines until "baseurl:"
  We are FIRST robotics team 2491 No Mythic from St. Paul, Minnesota.
   Made up of three small charter schools, we are the only metro Minnesota team to win a regional in the 2016 season!
   Come visit us at the FIRST World Championships!
baseurl: "http://lauraschultz.github.io/nomythic" # the subpath of your site, e.g. /blog/
url: "http://lauraschultz.github.io/nomythic" # the base hostname & protocol for your site

picture: ""


# Build settings
markdown: kramdown
