# Site settings
title: 2491 No Mythic
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://lauraschultz.github.io/nomythic" # the subpath of your site, e.g. /blog/
url: "http://lauraschultz.github.io/nomythic" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

picture: ""

# Build settings
markdown: kramdown
